version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - /home/vagrant/share/SpringTutorials/accessing-data-mysql/sqlqueries.sql:/sqlqueries.sql